dist: trusty
sudo: required
language: go
go_import_path: github.com/coralogix/go-coralogix-sdk
git:
  depth: 1
go:
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
before_install:
  - go get -t -v ./...
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: ""
  email:
    recipients:
      - eldar@coralogix.com
    on_success: change
    on_failure: always